baseURL = "/"
locale = "zh-cn"
title = "SML { ❄ } — SNOWARE Markup Language"
theme = "sml-docs"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT", "404"]
ignoreLogs = ["warning-goldmark-raw-html"]
relativeURLs = true

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "SML（SNOWARE Markup Language）与 BamZap 包管理器的独立站点"
